version: '3'

services:
  app:
    build:
      context: .
    ports:
      - 5000:5000
    environment:
      - MONGODB_HOST=mongodb://mongo:27017/todo
    depends_on:
      - mongo
  mongo:
    image: mongo:4.4

