version: '3'

services:
  mywebapp:
    build: .
    ports:
      - '5000:5000'

  nginx:
    image: nginx
    ports:
      - '80:80'
    volumes:
      - ./mywebapp.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - mywebapp
